#!/usr/bin/env python3
"""Prepare the local specimen from actual build outputs. Does not publish a site."""
from __future__ import annotations
import hashlib
import json
from pathlib import Path
import shutil
from fontTools.ttLib import TTFont

ROOT = Path(__file__).resolve().parents[1]

def main() -> None:
    dist, site = ROOT / 'dist', ROOT / 'site'
    report = json.loads((dist / 'build-report.json').read_text())
    if report['files'] != 96 or any(row['structural_check'] != 'passed' for row in report['records']):
        raise SystemExit('Prepare a complete checked build (96 files) first.')
    sources = sorted((dist / 'woff2').glob('*/*.woff2'))
    if len(sources) != 32:
        raise SystemExit('Expected 32 real WOFF2 faces.')
    records, css = [], ['/* Generated by tools/prepare_site.py; local candidate, license pending. */']
    cmap = None
    for source in sources:
        with TTFont(source) as font:
            family = font['name'].getDebugName(16)
            if family not in ('LihuiT', 'zayJu'):
                raise SystemExit(f'Unexpected family: {family}')
            weight = font['OS/2'].usWeightClass
            style = 'oblique 10deg' if font['post'].italicAngle else 'normal'
            this_cmap = font.getBestCmap()
            if cmap is not None and cmap != this_cmap:
                raise SystemExit('Character maps differ; per-face coverage is needed.')
            cmap = this_cmap
        target = site / 'fonts' / family / source.name
        target.parent.mkdir(parents=True, exist_ok=True)
        if target.is_symlink():
            raise SystemExit(f'Refusing to follow a destination symlink: {target}')
        shutil.copyfile(source, target)
        url = target.relative_to(site).as_posix()
        css.append(f'@font-face{{font-family:"{family}";src:url("{url}") format("woff2");font-weight:{weight};font-style:{style};font-display:block;}}')
        records.append({'file': url, 'family': family, 'weight': weight, 'style': style, 'sha256': hashlib.sha256(target.read_bytes()).hexdigest()})
    (site / 'fonts.css').write_text('\n'.join(css) + '\n')
    characters = [{'unicode': f'U+{cp:04X}', 'character': chr(cp), 'glyph': name} for cp, name in sorted(cmap.items())]
    (site / 'characters.json').write_text(json.dumps(characters, ensure_ascii=True, indent=2) + '\n')
    (site / 'font-manifest.json').write_text(json.dumps({'version': report['version'], 'state': 'local-candidate', 'license': 'pending', 'fonts': records}, indent=2) + '\n')
    print(f'Prepared {len(records)} webfonts and {len(characters)} character entries for local preview only.')
    print('Start: python -m http.server 8136 --bind 127.0.0.1 --directory site')

if __name__ == '__main__':
    main()
